version: '3'

tasks:
  docker_build:
    cmds:
      - docker compose build
  up:
    cmds:
      - docker compose up -d
  down:
    cmds:
      - docker compose down
  stop:
    cmds:
      - docker compose stop
  bash:
    cmds:
      - docker compose exec app /bin/bash
  yarn:
    cmds:
      - docker compose exec app yarn
  dev:
    cmds:
      - docker compose exec app yarn dev
